<template>
  <div
    class="column q-px-sm q-gutter-y-sm bg-pink-6 no-wrap"
    style="height: calc(100vh - 75px); overflow-y: auto"
  >
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
    <div>Avalon</div>
  </div>
</template>

<script setup>
//
</script>
